
services:

  unsloth:
    image: unsloth/unsloth:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    environment:
      JUPYTER_PASSWORD: ${UNSLOTH_JUPYTER_PASSWORD}
      UNSLOTH_USER_PASSWORD: ${UNSLOTH_USER_PASSWORD}
    ports:
      - 8888:8888
      - 8000:8000
      - 2222:22
    volumes:
      - ./unsloth/work:/workspace/work

  drupal:
    build: ./drupal
    environment:
      DRUPAL_DB_HOST: ${DRUPAL_DB_HOST}
      DRUPAL_DB_PORT: ${DRUPAL_DB_PORT}
      DRUPAL_DB_NAME: ${DRUPAL_DB_NAME}
      DRUPAL_DB_USER: ${DRUPAL_DB_USER}
      DRUPAL_DB_PASS: ${DRUPAL_DB_PASS}
      DRUPAL_SITE_NAME: ${DRUPAL_SITE_NAME}
      DRUPAL_ADMIN_USER: ${DRUPAL_ADMIN_USER}
      DRUPAL_ADMIN_PASS: ${DRUPAL_ADMIN_PASS}
    ports:
      - 8383:80
    volumes:
      - /var/www/html/sites
      - ./drupal/config:/opt/drupal/config
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${DRUPAL_DB_NAME}
      MARIADB_USER: ${DRUPAL_DB_USER}
      MARIADB_PASSWORD: ${DRUPAL_DB_PASS}
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 30s

  elasticsearch:
    image: elasticsearch:9.2.0
    environment:
      cluster.name: elasticsearch
      discovery.type: single-node
      node.name: es01
      xpack.security.enabled: false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    mem_limit: 10g
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  elasticsearch-data:
  mariadb-data:
